services:
  development:
    build:
      context: .
      dockerfile: ./Dockerfile.development
    image: mission/development:local
    working_dir: /open-mission
    container_name: open-mission-development
    command: [ "tail", "-f", "/dev/null" ]
    init: true
    tty: true
    stdin_open: true
    env_file:
      - ../.env
    environment:
      MISSIONS_PATH: /missions
      MISSION_CONFIG_PATH: /config
    volumes:
      - "../:/open-mission"
      - "../../flying-pillow:/flying-pillow"
      - "${HOST_REPOSITORIES_PATH:-/mnt/volatile/repositories}:/repositories"
      - "${HOST_MISSIONS_PATH:-/mnt/volatile/missions}:/missions"
      - "${HOST_MISSION_CONFIG_PATH:-/mnt/volatile/config}:/config"
      - "cargo-registry:/home/dev/.cargo/registry"
      - "cargo-git:/home/dev/.cargo/git"
      - "rustup:/home/dev/.rustup"
    expose:
      - "5174"
      - "1420"
      - "1421"
      - "9229"
      - "5900"
      - "6080"
    ports:
      - "5174:5174"
      - "1420:1420"
      - "1421:1421"
      - "5900:5900"
      - "6080:6080"

volumes:
  cargo-registry:
  cargo-git:
  rustup:
