services:
  development:
    build:
      context: .
      dockerfile: ./Dockerfile.development
    image: mission/development:local
    working_dir: /mission
    container_name: mission-development
    command: [ "tail", "-f", "/dev/null" ]
    init: true
    tty: true
    stdin_open: true
    env_file:
      - ../.env
    volumes:
      - "../:/mission"
      - "../../flying-pillow/dev/flying-pillow:/flying-pillow"
      - "cargo-registry:/home/dev/.cargo/registry"
      - "cargo-git:/home/dev/.cargo/git"
      - "rustup:/home/dev/.rustup"
    expose:
      - "5174"
      - "1420"
      - "1421"
      - "9229"
    ports:
      - "5174:5174"
      - "1420:1420"
      - "1421:1421"

volumes:
  cargo-registry:
  cargo-git:
  rustup:
